version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-comments
    environment:
      DB_HOST: dpg-cvp9bhgdl3ps73fumvmg-a.ohio-postgres.render.com  # Naudokite išorinį PostgreSQL serverio URL
      DB_NAME: mano_baze
      DB_USER: mano_baze_user
      DB_PASS: DRMN3D1p9QtJpttdZTAFFNqPdJb6jYux  # Naudokite tikrą slaptažodį
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
