version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-comments
    environment:
      DB_HOST: dpg-d0lfj2je5dus73chqna0-a.ohio-postgres.render.com  # Naudokite išorinį PostgreSQL serverio URL
      DB_NAME: mano_baze_iw6v
      DB_USER: mano_baze_user
      DB_PASS: vBE4W7bBF6myAzdWLKwrXAvuoNefG3M0  # Naudokite tikrą slaptažodį
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
