version: '3.8'

services:
  php:
    image: php:8.1-apache
    container_name: php-container
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - mynetwork
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mano_baze
    networks:
      - mynetwork
    ports:
      - 3306:3306

networks:
  mynetwork:
    driver: bridge
