version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-comments
    environment:
      DB_HOST: mysql
      DB_NAME: mano_baze
      DB_USER: root
      DB_PASS: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mano_baze
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
