version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql  # Naudojame 'mysql', nes Docker Compose pagal nutylėjimą sukuria tinklą
      - DB_NAME=mano_baze
      - DB_USER=root
      - DB_PASS=rootpassword
    depends_on:
      - mysql  # PHP konteineris laukia, kol MySQL paslauga bus paruošta
    networks:
      - mynetwork
    ports:
      - "80:80"  # PHP konteineris naudoja prievadą 80

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mano_baze
    networks:
      - mynetwork
    ports:
      - "3306:3306"  # MySQL konteineris naudoja prievadą 3306

networks:
  mynetwork:
    driver: bridge
